empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'departamento_app'
urlpatterns = [
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name = 'new_departament'
    ),
    path(
        'lista-departamento/',
        views.DepartamentoListView.as_view(),
        name = 'departament_lista'
    ),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
        ),
    #'.as_view() ' method when is used generic view 
    #1.- Listar todos los empleados de la empresa
    path(
        'list-all-employee/',
        views.ListAllEmpleados.as_view(),
        name ='empleado_all'
    ),
    #2.- Listar todos los empleados que perteneces a un area de la empresa
    path(
        'list-by-area/<shortname>/',
        views.ListByArea.as_view(),
        name='empleados_area'
        ),
    #search a employee by kword
    path('search-employee/',views.ListEmpleadosByKword.as_view()),
    #list employee skills
    path('skills-employee/',views.ListSkillsEmployee.as_view()),
    #Detailview 
    path(
        'see-employee/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    #CreateView
    path(
        'add-employee/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    #templateview need a template is used call other template 
    path(
        'sucess/',
        views.SucessView.as_view(),
        name='correcto'
        ),
    path(
        'update-employee/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
        ),
    path(
        'delete-employee/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='borrar_empleado'
        ),
    path(
        'list-employee-admin/',
        views.ListAllEdmin.as_view(),
        name='empleado_admin'
        ),
    
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.persona.urls')),
    re_path('',include('applications.home.urls'))
    #static() -> we can show img in browser
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">Empleados</li>
            <li>
            <a href="{% url 'persona_app:empleado_all' %}">Empleados</a>
            </li>
            <li><a href="{% url 'departamento_app:departament_lista' %}">Departamentos</a></li>
            <li><a href="{% url 'persona_app:empleado_admin' %}">Administrar</a></li>
            <li><a href="{% url 'departamento_app:new_departament' %}">Nuevo Departamento</a></li>
        </ul>
        </div>
        <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Buscar Empleado"></li>
            <li><a class="button" href="{% url 'persona_app:empleado_add' %}">Registrar Nuevo</a></li>
        </ul>
    </div>
</div>