empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
        ),
    #'.as_view() ' method when is used generic view 
    #1.- Listar todos los empleados de la empresa
    path(
        'list-all-employee/',
        views.ListAllEmpleados.as_view(),
        name ='empleado_all'
    ),
    #2.- Listar todos los empleados que perteneces a un area de la empresa
    path(
        'list-by-area/<shortname>/',
        views.ListByArea.as_view(),
        name='empleados_area'
        ),
    #search a employee by kword
    path('search-employee/',views.ListEmpleadosByKword.as_view()),
    #list employee skills
    path('skills-employee/',views.ListSkillsEmployee.as_view()),
    #Detailview 
    path(
        'see-employee/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    #CreateView
    path(
        'add-employee/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    #templateview need a template is used call other template 
    path(
        'sucess/',
        views.SucessView.as_view(),
        name='correcto'
        ),
    path(
        'update-employee/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
        ),
    path(
        'delete-employee/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='borrar_empleado'
        ),
    path(
        'list-employee-admin/',
        views.ListAllEdmin.as_view(),
        name='empleado_admin'
        ),
    
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.persona.urls')),
    re_path('',include('applications.home.urls'))
    #static() -> we can show img in browser
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/persona/models.py
from django.db import models
from ckeditor.fields import RichTextField
from applications.departamento.models import Departamento

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)
    
    class Meta:
        verbose_name= 'Habilidad'
        verbose_name_plural= 'Habilidad Empleados'
    
    def __str__(self) -> str:
        return str(self.id)+' - ' + self.habilidad

# Create your models here.
class Empleado(models.Model):
    '''Model for employee table'''
    '''Contador, Administrador, Economista'''
    JOB_CHOICES=(
        ('0','Contador'),
        ('1','Administrador'),
        ('2','Economista'),
        ('3','Otro'),
        
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombres Completos', 
        max_length=50,
        blank=True
        )
    job = models.CharField('Trabajo', max_length=50,choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    
    class Meta:
        verbose_name= 'Empleado Administrativo'
        verbose_name_plural= 'Empleados de las Areas'
        ordering =['id']
        unique_together=('first_name','last_name')
    
    def __str__(self) -> str:
        return str(self.id) + ' ' + self.first_name + ' - ' + self.last_name
    

empleado/applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import(
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)
#1.- Listar todos los empleados de la empresa
#2.- Listar todos los empleados que perteneces a un area de la empresa
#3.- Listar empleados por trabajo
#4.- Listar los empleados por la palabra clave
#5.- listar habilidades de un empleado
#models
from .models import Empleado
# Create your views here.

#class of extends templates html 

class InicioView(TemplateView):
    '''Vista que carga la pagina de inicio'''
    template_name = 'inicio.html'

#1.- Listar todos los empleados de la empresa
class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering= 'id'
    
    def get_queryset(self):
        key_word= self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(
            full_name__icontains = key_word
        )
        print("La lista resultante es: ",lista)
        return lista
    
#2.- Listar todos los empleados que perteneces a un area de la empresa
class ListByArea(ListView):
    template_name = 'persona/list_by_area.html'
    context_object_name='empleados'
    
    #return a employees list by filter short_name
    def get_queryset(self):
        area = self.kwargs['shortname']
        print("Kwargs: ", area)
        lista = Empleado.objects.filter(
            departamento__short_name = area
        )
        print("La lista es : ", lista)
        return lista

class ListEmpleadosByKword(ListView):
    # employees list by kword
    template_name= 'persona/by_kword.html'
    context_object_name = 'empleado'
    
    def get_queryset(self):
        print("**********************************")
        key_word= self.request.GET.get("kword",'')
        print("Request: ",self.request)
        print(key_word)
        print("==================================")
        lista = Empleado.objects.filter(
        first_name = key_word
        )
        print("La lista resultante es: ",lista)
        return lista
    
class ListSkillsEmployee(ListView):
    template_name = 'persona/skill.html'
    context_object_name = 'skills'
    
    def get_queryset(self):
        #return one employee
        id_employee = self.request.GET.get("kword",'')
        print("id employee",id_employee)
        empleado = Empleado.objects.get(id=id_employee)
        #print(" Habilidades del empleado: \n",empleado.habilidades.all())
        
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_employee.html"
    context_object_name='empleado'
    
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo']=' Empleado del mes'
        return context
    

class SucessView(TemplateView):
    template_name = "persona/sucess.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add_empleado.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'avatar',
        ]#('__all__')
    #self direction
    success_url = reverse_lazy('persona_app:empleado_admin')
    #track the form and update fields full_name
    def form_valid(self, form):
        empleado = form.save()#content all data of form employee
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        #methode override class EmpleadoCreateView
        return super(EmpleadoCreateView, self).form_valid(form)




class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        ]
    success_url= reverse_lazy('persona_app:empleado_admin')
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print("================METHODE POST================")
        #retrieve a tupla of POST request
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        print("================METHODE FORM VALID================")
        return super(EmpleadoUpdateView, self).form_valid(form)
    

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url= reverse_lazy('persona_app:empleado_admin')


#--------------------------------------------------------------------------
class ListAllEdmin(ListView):
    template_name = 'persona/list_all_admin.html'
    paginate_by = 10
    ordering= 'id'
    context_object_name='empleados'
    model=Empleado
    

empleado/templates/persona/add_empleado.html
{% extends 'base.html' %}

{% block title %}
    Registrar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cel">
            Registrar Empleado
        </h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="cell large-6 ">
                <label>Nombres:
                  {{ form.first_name}}
                </label>
            </div>
            <div class="cell large-6 ">
                <label>Apellidos:
                  {{ form.last_name}}
                </label>
            </div>
            <div class="cell large-6 ">
                <label>Trabajo:
                  {{ form.job}}
                </label>
            </div>
            <div class="cell large-6 ">
                <label>Area:
                  {{ form.departamento}}
                </label>
            </div>
            <div class="cell large-6 ">
                <label>habilidades Extra:
                  {{ form.habilidades}}
                </label>
            </div>
            <div class="cell large-6 ">
                <label>Foto:
                  {{ form.avatar}}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="success button">Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

empleado/templates/persona/by_kword.html
<h1>Buscar Empleado por Palabra Clave</h1>
<form method="GET">
    {% csrf_token %} 
    <input type="text" name="kword" id="kword" placeholder="Ingrese Nombre Aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultante</h3>

<ul>
    
    {% for e in empleado %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

empleado/templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar Empleado
{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{object.full_name}}</h1>
        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout secondary">
                <h5>¿Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

empleado/templates/persona/detail_employee.html
<!-- 1.- Listar todos los empleados de la empresa -->
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{empleado.full_name}}
{% endblock title %}
    

<!-- body -->
{% block content %}
<!-- header -->
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell medium-4 card" style="width: 300px;">
            <div class="card-divider callout">
              {{empleado.get_job_display}}
            </div>
            
            {% if empleado.avatar %}
                <img src="{{empleado.avatar.url}}">
            {% else %}
                <img src="{% static 'img/cr7.jpeg' %}" alt="">
            {% endif %}
            <div class="card-section" style="text-align: center;">
              <h4>{{empleado.full_name}}</h4>
              <p>{{empleado.first_name}}</p>
              <p>{{empleado.departamento.short_name}}</p>
              <p>{{empleado.habilidades}}</p>

            </div>
          </div>
    </div>
    <div class="cell">
        <nav>
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">Atras</a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    <li {% if page_obj.number == i %} class="active" {% endif %}>
                        <a href="?page={{i}}">{{ i }}</a>
                    </li> 
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">Siguiete</a></li>
                {% endif %}
            </ul>
        {% endif %}
        </nav> 
    </div>
</div>
{% endblock content %}

empleado/templates/persona/list_all.html
<!-- 1.- Listar todos los empleados de la empresa -->
{% extends 'base.html' %}


<!-- body -->
{% block content %}
<!-- header -->
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x grid-padding-x">
        <h1 class="large-12 cell">Lista Empleados</h1>
        <form method="GET" class="cell grid-x grid-margin-x">
            {% csrf_token %}
            <div class="large-7 medium-7 cell">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
            </div>
            <div class="large-2 medium-2 cell">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTOS</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                    <tbody>
                        {% for e in object_list %}
                        <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <!-- url: set of url + identifier e.id -->
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                        {% endfor %}
                        </tr>
                    </tbody>
            </table>
        </div>
    </div>
    <div class="cell">
        <nav>
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">Atras</a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    <li {% if page_obj.number == i %} class="active" {% endif %}>
                        <a href="?page={{i}}">{{ i }}</a>
                    </li> 
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">Siguiete</a></li>
                {% endif %}
            </ul>
        {% endif %}
        </nav> 
    </div>
</div>
{% endblock content %}
    

empleado/templates/persona/list_all_admin.html
{% extends 'base.html' %}

{% block title %}
    Lista Empleados Administrativos
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-padding-x">
        <h1 class="large-12 cell">Administrador</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th width="200">NOMBRES</th>
                        <th width="200">APELLIDOS</th>
                        <th width="100">TRABAJO</th>
                        <th width="150">DEPARTAMENTOS</th>
                        <th width="100">ACCION</th>
                    </tr>
                </thead>
                    <tbody>  
                        {% for empleado in empleados %}
                        <tr>
                            <td>{{empleado.id}}</td>
                            <td>{{empleado.first_name}}</td>
                            <td>{{empleado.last_name}}</td>
                            <td>{{empleado.job}}</td>
                            <td>{{empleado.departamento}}</td>
                            <td><a class="button success" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a></td>
                            <td><a class="button alert" href="{% url 'persona_app:borrar_empleado' empleado.id %}">Eliminar</a></td>
                        </tr>
                        {% endfor %} 
                    </tbody>
            </table>
        </div>
    </div>
    <div class="cell">
        <nav>
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">Atras</a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    <li {% if page_obj.number == i %} class="active" {% endif %}>
                        <a href="?page={{i}}">{{ i }}</a>
                    </li> 
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">Siguiete</a></li>
                {% endif %}
            </ul>
        {% endif %}
        </nav> 
    </div>
</div>
{% endblock content %}
    

empleado/templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block title %}
    Lista de Empleados por Departamento
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Lista Empleados por Departamentos
        </h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NOMBRES</th>
                        <th>APELLIDOS</th>
                        <th>DEPARTAMENTO</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{empleado.id}}</td>
                        <td>{{empleado.first_name}}</td>
                        <td>{{empleado.last_name}}</td>
                        <td>{{empleado.departamento}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}


    

empleado/templates/persona/skill.html
<h1>Habilidades de los Empleados</h1>
<form method="GET">
    {% csrf_token %} 
    <input type="text" name="kword" id="kword" placeholder="Ingrese C.C Aqui">
    <button type="submit">Buscar</button>
</form>

<ul>
    
    {% for e in skills %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

empleado/templates/persona/sucess.html
<h1>Felicitaciones se guardo el empleado correctamente</h1>

empleado/templates/persona/update.html
{% extends 'base.html' %}

{% block title %}
    Editar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST"> {% csrf_token %}
                <div class="cell large-6 ">
                    <label>Nombres:
                      {{ form.first_name}}
                    </label>
                </div>
                <div class="cell large-6 ">
                    <label>Apellidos:
                      {{ form.last_name}}
                    </label>
                </div>
                <div class="cell large-6 ">
                    <label>Trabajo:
                      {{ form.job}}
                    </label>
                </div>
                <div class="cell large-6 ">
                    <label>Area:
                      {{ form.departamento}}
                    </label>
                </div>
                <div class="cell large-6 ">
                    <label>habilidades Extra:
                      {{ form.habilidades}}
                    </label>
                </div>
                <div class="cell medium-2">
                    <button type="submit" class="success button">Guardar</button>
                </div>
               
            </form>
        </div>
    </div>
</div>


{% endblock content %}
    
    