empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'departamento_app'
urlpatterns = [
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name = 'new_departament'
    ),
    path(
        'lista-departamento/',
        views.DepartamentoListView.as_view(),
        name = 'departament_lista'
    ),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
        ),
    #'.as_view() ' method when is used generic view 
    #1.- Listar todos los empleados de la empresa
    path(
        'list-all-employee/',
        views.ListAllEmpleados.as_view(),
        name ='empleado_all'
    ),
    #2.- Listar todos los empleados que perteneces a un area de la empresa
    path(
        'list-by-area/<shortname>/',
        views.ListByArea.as_view(),
        name='empleados_area'
        ),
    #search a employee by kword
    path('search-employee/',views.ListEmpleadosByKword.as_view()),
    #list employee skills
    path('skills-employee/',views.ListSkillsEmployee.as_view()),
    #Detailview 
    path(
        'see-employee/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    #CreateView
    path(
        'add-employee/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    #templateview need a template is used call other template 
    path(
        'sucess/',
        views.SucessView.as_view(),
        name='correcto'
        ),
    path(
        'update-employee/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
        ),
    path(
        'delete-employee/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='borrar_empleado'
        ),
    path(
        'list-employee-admin/',
        views.ListAllEdmin.as_view(),
        name='empleado_admin'
        ),
    
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.persona.urls')),
    re_path('',include('applications.home.urls'))
    #static() -> we can show img in browser
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre corto', max_length=50, unique=True)
    anulate = models.BooleanField('Anulado',default=False)
    
    class Meta:
        verbose_name= 'Mi Departamento'
        verbose_name_plural= 'Areas de la Empresa'
        ordering =['name']
        unique_together=('name','short_name')
    
    def __str__(self) -> str:
        return str(self.id) + '  -  ' + self.name + '  -  ' + self.short_name

empleado/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField( max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    short_name = forms.CharField(max_length=50)
    

empleado/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.views.generic.edit import(
    FormView,
)
from applications import departamento
from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista-departamentos.html"
    context_object_name = 'departamentos'


# Create your views here.
class NewDepartamentoView(FormView):
    template_name='departamento/new_departament.html'
    form_class = NewDepartamentoForm
    success_url='/'
    
    def form_valid(self, form):
        print("Estamos en el form valid")
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name=form.cleaned_data['short_name']
        )
        depa.save()
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job=1,
            departamento = depa
        )
        return super(NewDepartamentoView,self).form_valid(form)

empleado/templates/departamento/lista-departamentos.html
{% extends 'base.html' %}

{% block title %}
Lista de Departamentos
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Lista Departamentos
        </h1>
        <div class="cell">
            <table>
                <tbody>
                    {% for departamento in departamentos %}
                    <tr>
                        <td>{{departamento.id}}</td>
                        <td>{{departamento.name}}</td>
                        <td>{{departamento.short_name}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleados_area' departamento.short_name %}">Ver Empleados</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}
    

empleado/templates/departamento/new_departament.html
{% extends 'base.html' %}

{% block title %}
    Registrar Departamento
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cel">
            Registrar Departamento
        </h1>
        <form class="cell callout grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                  {{ form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                  {{ form.apellidos}}
                </label>
            </div>
            <div class="medium-6 cell ">
                <label>Area:
                  {{ form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell ">
                <label>Nombre Corto:
                  {{ form.short_name}}
                </label>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}